### ISSUE TITLE
Get Error: cannot load such file -- temple/static_analyzer (LoadError)

### ISSUE THREAD

**Issue by wimrijnders** [haml/haml#1001]
Hi there, I'm installing my web server on a squeaky clean Debian distro. 

On generation, I get an error, with a traceback ending in:

```
...
4: from /home/wim/.rvm/gems/ruby-2.5.1-latest/gems/haml-5.0.4/lib/haml/compiler.rb:31:in `compile'
3: from /home/wim/.rvm/gems/ruby-2.5.1-latest/gems/haml-5.0.4/lib/haml/compiler.rb:110:in `compile_tag'
2: from /home/wim/.rvm/gems/ruby-2.5.1-latest/gems/haml-5.0.4/lib/haml/attribute_compiler.rb:46:in `compile'
1: from /home/wim/.rvm/gems/ruby-2.5.1-latest/gems/haml-5.0.4/lib/haml/attribute_parser.rb:22:in `available?'
/home/wim/.rvm/gems/ruby-2.5.1-latest/gems/haml-5.0.4/lib/haml/attribute_parser.rb:22:in `require': cannot load such file -- temple/static_analyzer (LoadError)
```
As is evident, this is with ruby v2.5.1.

By experimentation, I found that the error disappears if I add a `require` to the top of `lib/haml/attribute_parser.rb`:

```ruby
require 'temple/static_analyzer'
```

Would you mind checking this out, and ensuring it doesn't happen any more?

For completeness, I mention that the same thing happens with [Hamlit](https://github.com/k0kubun/hamlit), so it might be an issue with the `temple` gem. However, since the require is so effective, I'm hoping that you can compensate within the `Haml` code.

**Comment by wimrijnders** [comment]
Thank you! Will check regularly for `haml` new version.
