### ISSUE TITLE
missing template error with Rails 7

### ISSUE THREAD

**Issue by IanPurdom** [haml/haml#1080]
Hi,

Working currently on projet with Rails 7, ruby 3.1.0 and Docker
For some reasons it doesn't load haml files.
I changed all the view files to .haml (mostly layout).
It's working perfectly with erb.
No error in bundle install.

Here's my gem file:

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "active_type"
gem "bcrypt"
gem "bootsnap", require: false
gem 'haml'
gem "haml-rails", "~> 2.0"
gem 'httparty'
gem "importmap-rails"
gem "pg", "~> 1.1"
gem "pgcli-rails"
gem "puma", "~> 5.0"
gem "rack-canonical-host"
gem "rails", "~> 7.0.1"
gem "sidekiq-cron", "~> 1.1"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem 'redis'
gem 'nokogiri', '~> 1.11', '>= 1.11.7'
gem 'watir'
gem 'webdrivers', '~> 5.0', require: false

group :production do
  gem "postmark-rails"
  gem "sidekiq"
end

group :development do
  gem "amazing_print"
  gem "annotate"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "letter_opener"
  gem "rubocop", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "web-console"
end

group :development, :test do
  gem "byebug"
  gem "dotenv-rails"
end

group :test do
  gem "capybara"
  gem "minitest-ci", require: false
  gem "selenium-webdriver"
  gem "shoulda-context"
  gem "shoulda-matchers"
  gem 'webdrivers', '~> 5.0', require: false
end
```

Below the error I get:
```

ActionController::MissingExactTemplate (HomeController#index is missing a template for request formats: text/html):
app_1       |
app_1       | actionpack (7.0.1) lib/action_controller/metal/implicit_render.rb:45:in `default_render'
app_1       | actionpack (7.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
app_1       | <internal:kernel>:90:in `tap'
app_1       | actionpack (7.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
app_1       | actionpack (7.0.1) lib/abstract_controller/base.rb:214:in `process_action'
app_1       | actionpack (7.0.1) lib/action_controller/metal/rendering.rb:53:in `process_action'
app_1       | actionpack (7.0.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
app_1       | activesupport (7.0.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
app_1       | actiontext (7.0.1) lib/action_text/rendering.rb:20:in `with_renderer'
app_1       | actiontext (7.0.1) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
app_1       | activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `instance_exec'
app_1       | activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
app_1       | activesupport (7.0.1) lib/active_support/callbacks.rb:138:in `run_callbacks'
app_1       | actionpack (7.0.1) lib/abstract_controller/callbacks.rb:233:in `process_action'
app_1       | actionpack (7.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
app_1       | actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
app_1       | activesupport (7.0.1) lib/active_support/notifications.rb:206:in `block in instrument'
app_1       | activesupport (7.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
app_1       | activesupport (7.0.1) lib/active_support/notifications.rb:206:in `instrument'
app_1       | actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
app_1       | actionpack (7.0.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
app_1       | activerecord (7.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
app_1       | actionpack (7.0.1) lib/abstract_controller/base.rb:151:in `process'
app_1       | actionview (7.0.1) lib/action_view/rendering.rb:39:in `process'
app_1       | actionpack (7.0.1) lib/action_controller/metal.rb:188:in `dispatch'
app_1       | actionpack (7.0.1) lib/action_controller/metal.rb:251:in `dispatch'
app_1       | actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
app_1       | actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
app_1       | actionpack (7.0.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
app_1       | actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
app_1       | actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
app_1       | actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:850:in `call'
app_1       | rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
app_1       | rack (2.2.3) lib/rack/etag.rb:27:in `call'
app_1       | rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
app_1       | rack (2.2.3) lib/rack/head.rb:12:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
app_1       | rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
app_1       | rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/cookies.rb:693:in `call'
app_1       | activerecord (7.0.1) lib/active_record/migration.rb:603:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
app_1       | activesupport (7.0.1) lib/active_support/callbacks.rb:99:in `run_callbacks'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
app_1       | web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
app_1       | web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
app_1       | web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
app_1       | web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
app_1       | railties (7.0.1) lib/rails/rack/logger.rb:36:in `call_app'
app_1       | railties (7.0.1) lib/rails/rack/logger.rb:25:in `block in call'
app_1       | activesupport (7.0.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
app_1       | activesupport (7.0.1) lib/active_support/tagged_logging.rb:37:in `tagged'
app_1       | activesupport (7.0.1) lib/active_support/tagged_logging.rb:99:in `tagged'
app_1       | railties (7.0.1) lib/rails/rack/logger.rb:25:in `call'
app_1       | sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
app_1       | rack (2.2.3) lib/rack/method_override.rb:24:in `call'
app_1       | rack (2.2.3) lib/rack/runtime.rb:22:in `call'
app_1       | activesupport (7.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/static.rb:23:in `call'
app_1       | rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
app_1       | actionpack (7.0.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
app_1       | railties (7.0.1) lib/rails/engine.rb:530:in `call'
app_1       | puma (5.6.1) lib/puma/configuration.rb:252:in `call'
app_1       | puma (5.6.1) lib/puma/request.rb:77:in `block in handle_request'
app_1       | puma (5.6.1) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
app_1       | puma (5.6.1) lib/puma/request.rb:76:in `handle_request'
app_1       | puma (5.6.1) lib/puma/server.rb:441:in `process_client'
app_1       | puma (5.6.1) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
app_1       | Started GET "/" for 172.30.0.1 at 2022-03-05 07:22:18 +0000
app_1       | Cannot render console from 172.30.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
app_1       | Processing by HomeController#index as HTML
app_1       | Completed 406 Not Acceptable in 3ms (ActiveRecord: 0.0ms | Allocations: 543)
app_1       |


```

**Comment by IanPurdom** [comment]
Ok sorry, it's a docker issue, needed to remove the volume dedicated to gem file

**Comment by k0kubun** [comment]
:+1: Glad it's resolved.
