### ISSUE TITLE
Possible breaking changes between 5.1.0 and 5.2.0

### ISSUE THREAD

**Issue by NotMyFault** [haml/haml#1119]
Hey,

I'm currently in the process of updating haml from 5.1.0 to 5.2.0, but I'm unable to get a passing build, yet there are no breaking changes noted in the changelog.
My build fails with the following exception:
```
[2022-12-19T16:56:26.331Z] Call to unknown method: third_party_href
[2022-12-19T16:56:26.331Z] An error during rendering /download/index.html.haml occurred.
[2022-12-19T16:56:26.331Z] While processing file /home/jenkins/workspace/Websites_jenkins.io_PR-5801/content/download/index.html.haml
[2022-12-19T16:56:26.331Z] An error occurred: undefined method `each' for nil:NilClass
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/haml-5.2.2/lib/haml/attribute_builder.rb:13:in `block in build'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/haml-5.2.2/lib/haml/attribute_builder.rb:11:in `each'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/haml-5.2.2/lib/haml/attribute_builder.rb:11:in `build'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/content/download/index.html.haml:118:in `__tilt_211820'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `call'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `evaluate'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/tilt-2.0.11/lib/tilt/haml.rb:24:in `evaluate'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/tilt-2.0.11/lib/tilt/template.rb:109:in `render'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/page.rb:143:in `rendered_content'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/engine.rb:428:in `generate_page'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/engine.rb:404:in `block in generate_output'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:472:in `process_incoming_jobs'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:454:in `block in worker'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `fork'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `worker'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:436:in `block in create_workers'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each_with_index'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `create_workers'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:374:in `work_in_processes'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:278:in `map'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/engine.rb:402:in `generate_output'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/engine.rb:121:in `run'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/cli/generate.rb:22:in `run'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/cli/invoker.rb:152:in `invoke_generate'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/lib/awestruct/cli/invoker.rb:74:in `invoke!'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/gems/awestruct-0.6.1/bin/awestruct:9:in `<top (required)>'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/bin/awestruct:23:in `load'
[2022-12-19T16:56:26.331Z] /home/jenkins/workspace/Websites_jenkins.io_PR-5801/vendor/gems/ruby/2.7.0/bin/awestruct:23:in `<top (required)>'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
[2022-12-19T16:56:26.331Z] /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
[2022-12-19T16:56:26.331Z] /usr/local/bin/bundle:23:in `load'
[2022-12-19T16:56:26.331Z] /usr/local/bin/bundle:23:in `<main>'
```
The relevant code parts are here:
- https://github.com/jenkins-infra/jenkins.io/blob/b2e9d8be0e7575425431db21c2cf06ba20e26108/content/download/index.html.haml#L7
- https://github.com/jenkins-infra/jenkins.io/blob/b2e9d8be0e7575425431db21c2cf06ba20e26108/content/project/roadmap/index.html.haml#L14

Am I missing something, or is there anything else I need to do when updating haml?

Thanks in advance!

**Comment by k0kubun** [comment]
Can you reproduce the same issue with a single Haml file that could be rendered with `haml` command? Haml maintainers are not necessarily sure how to evaluate your index.html.haml.

Also, have you tried the same thing with Haml 6? We no longer maintain Haml 5, so even if it's broken, we'll only push a fix to Haml 6.

**Comment by NotMyFault** [comment]
> Also, have you tried the same thing with Haml 6? We no longer maintain Haml 5, so even if it's broken, we'll only push a fix to Haml 6.

We're using [awestruct](https://github.com/awestruct/awestruct), which requires a haml version between >= 4.0.5 and< 6.0 :/

**Comment by k0kubun** [comment]
Please report that to awestruct or consider temporarily forking it. We don't control that library.

Anyway, I'll wait for a standalone template that reproduces the problem. It doesn't seem actionable on Haml maintainers' end.

**Comment by zbynek** [comment]
I think this is more `tilt` issue than `haml` issue, something to do with scope of compiled methods (update of `haml` triggered update of `tilt`, and that alone is enough to reproduce the issue.

**Comment by k0kubun** [comment]
Thanks for working on that. Now that https://github.com/jenkins-infra/jenkins.io/pull/5969 is closed, I'm going to close this.
