### ISSUE TITLE
uninitialized constant Haml::ActionView with 4.0.3

### ISSUE THREAD

**Issue by dpogue** [haml/haml#695]
I would get this error when trying to run spec tests in my Rails engine using Haml 4.0.3:

```bash
$ bundle exec rake spec
rake aborted!
uninitialized constant Haml::ActionView
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml/helpers/safe_erubis_template.rb:3:in `<module:Haml>'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml/helpers/safe_erubis_template.rb:1:in `<top (required)>'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml/railtie.rb:21:in `require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml/railtie.rb:21:in `<top (required)>'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml.rb:23:in `require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/haml-4.0.3/lib/haml.rb:23:in `<top (required)>'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/Users/dpogue/.rvm/gems/ruby-1.9.3-p429@mygem/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/Users/dpogue/workspace/Rakefile:8:in `<top (required)>'
```

My Gemfile contains the following:

```ruby
gem 'rails', '~> 3.2.12'

gem 'haml'
gem 'haml-rails'
```

I was able to fix this error by adding `require 'action_view'` to lib/haml/helpers/safe_erubis_template.rb, but I don't know whether that's the correct fix or whether I'm missing a dependency somewhere.

**Comment by posgarou** [comment]
I am also running into the same error (even a year and a half later), and your fix worked for me as well.

**Comment by bibstha** [comment]
Could you release a 4.0.x version with this update on it?

**Comment by gottfrois** [comment]
Any news regarding bumping a version with this fix?

**Comment by fwolfst** [comment]
I get the same error when using haml in a gem (created with `bundle gem new ...`) that also has sinatra as dependency (no rails) when `bundle console`ing.

Adding a `require "action_view"` at prominent place solves the issue for me, but it seems odd to have to do that.

**Comment by cema-sp** [comment]
Please add that fix to stable version
