### ISSUE TITLE
Haml::SyntaxError when working with haml, erb and pygments in nanoc

### ISSUE THREAD

**Issue by matthiasbeyer** [haml/haml#857]
Hi,

I'm working on a wiki template build with nanoc, the static site compiler. I use haml and erb as well as pygements, so this is rather complex I guess.

Here is the backtrace nanoc comes up with:

```
Crashlog created at 2015-09-04 18:32:03 +0200

===== MESSAGE:

Haml::SyntaxError: item /articles/the_wiki.haml (rep default):34: syntax error, unexpected keyword_end, expecting end-of-input
...iki\nreturn 6\n", 0, false);end;_hamlout.buffer << _hamlout....
...                               ^

===== COMPILATION STACK:

  - [item]   /articles/the_wiki.haml (rep default)

===== STACK TRACE:

  0. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/engine.rb:131:in `rescue in render'
  1. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/engine.rb:128:in `render'
  2. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/filters/haml.rb:21:in `run'
  3. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
  4. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/services/executor.rb:36:in `filter'
  5. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/rule_context.rb:39:in `filter'
  6. /home/m/archive/development/ruby/wiki.template/Rules:19:in `block in parse'
  7. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/rule.rb:69:in `instance_exec'
  8. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/rule.rb:69:in `apply_to'
  9. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/compiler.rb:390:in `compile_rep'
  10. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/compiler.rb:343:in `block in compile_reps'
  11. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/compiler.rb:336:in `loop'
  12. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/compiler.rb:336:in `compile_reps'
  13. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/compilation/compiler.rb:93:in `run'
  14. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/base/source_data/site.rb:23:in `compile'
  15. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/commands/compile.rb:376:in `block in run'
  16. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/commands/compile.rb:418:in `run_listeners_while'
  17. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/commands/compile.rb:375:in `run'
  18. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/command_runner.rb:12:in `block in call'
  19. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  20. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  21. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/command_runner.rb:11:in `call'
  22. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  23. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  24. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  25. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  26. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/commands/nanoc.rb:37:in `block in define'
  27. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  28. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  29. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  30. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli.rb:53:in `block in run'
  31. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  32. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  33. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli.rb:51:in `run'
  34. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/bin/nanoc:9:in `<top (required)>'
  35. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

Nanoc 4.0.0rc2 © 2007-2015 Denis Defreyne.
Running ruby 2.2.0 (2014-12-25) on x86_64-linux with RubyGems 2.4.1.

===== SYSTEM INFORMATION:

Linux yuu 3.18.20 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux

===== INSTALLED GEMS:

  adsf 1.2.0
  bundler 1.10.5
  chunky_png 1.3.4
  coderay 1.1.0
  colored 1.2
  compass 1.0.3
  compass-core 1.0.3
  compass-import-once 1.0.5
  cri 2.7.0
  ffi 1.9.10
  haml 4.0.7
  kramdown 1.8.0
  method_source 0.8.2
  mini_portile 0.6.2
  multi_json 1.11.2
  nanoc 4.0.0rc2
  nokogiri 1.6.6.2
  posix-spawn 0.3.11
  pry 0.10.1
  pygments.rb 0.6.3
  rack 1.6.4
  rb-fsevent 0.9.6
  rb-inotify 0.9.5
  sass 3.4.18
  slop 3.6.0
  tilt 2.0.1
  yajl-ruby 1.2.1
  zurb-foundation 4.3.2

===== ENVIRONMENT:

BUNDLE_BIN_PATH => "/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/bin/bundle"
BUNDLE_GEMFILE => "/home/m/archive/development/ruby/wiki.template/Gemfile"
CC => "gcc"
CONFIG_DIR => "~./config"
CONFIG_SHELL => "/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash"
CXX => "g++"
DBUS_SESSION_BUS_ADDRESS => "unix:abstract=/tmp/dbus-PqignhH5iQ,guid=99f34fa7e2589bbf40e185f155e60aee"
DISPLAY => ":0.0"
EDITOR => "vim"
GEM_HOME => "/home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0"
GEM_PATH => ""
GIT_SSL_CAINFO => "/etc/ssl/certs/ca-certificates.crt"
GTK_PATH => "/home/m/.nix-profile/lib/gtk-2.0:/home/m/.nix-profile/lib/gtk-3.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/default/lib/gtk-3.0:/run/current-system/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0"
HOME => "/home/m"
HOST_COLOR => "\\e[1;30m"
INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH => "20"
INFINALITY_FT_FILTER_PARAMS => "08 24 36 24 08"
INFINALITY_FT_FRINGE_FILTER_STRENGTH => "50"
INFINALITY_FT_USE_VARIOUS_TWEAKS => "true"
INFOPATH => "/home/m/.nix-profile/info:/home/m/.nix-profile/share/info:/nix/var/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info"
IN_NIX_SHELL => "1"
KDEDIRS => "/home/m/.nix-profile:/nix/var/nix/profiles/default:/run/current-system/sw"
LANG => "de_DE.UTF-8"
LD_LIBRARY_PATH => "/run/opengl-driver/lib:/run/opengl-driver-32/lib"
LIBEXEC_PATH => "/home/m/.nix-profile/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec"
LIBVA_DRIVERS_PATH => "/nix/store/8hl7vq4lm55613rh3dl4h7dlp84ndv1m-vaapi-drivers/lib/dri"
LOCALE_ARCHIVE => "/run/current-system/sw/lib/locale/locale-archive"
LOCATE_PATH => "/var/cache/locatedb"
LOGNAME => "m"
LS_COLORS => "no=00:fi=00:di=00;33:ln=00;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=01;30:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:*.tar=00;31:*.tgz=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.zip=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.jpg=00;36:*.gif=00;36:*.bmp=00;36:*.xbm=00;36:*.xpm=00;36:*.tif=00;36:*.tga=00;36:*.png=00;36:*.jpeg=00;36:*.tiff=00;36:*.xcf=00;36:*.xcf.gz=00;36:*.blend=00;36:*.pcx=00;36:*.ppm=00;36:*.mp3=00;32:*.mid=00;32:*.wav=00;32:*.au=00;32:*.nes=00;31:*.smc=00;31:*.fig=00;31:*.sfc=00;31:*.smc.gz=00;31:*.fig.gz=00;31:*.sfc.gz=00;31:*.mpg=00;35:*.mpeg=00;35:*.avi=00;35:*.mov=00;35:*.fli=00;35:*.flc=00;35:*.pdf=00;36:"
MAIL => "/var/mail/m"
MANPATH => "/home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/kramdown-1.8.0/man"
MODULE_DIR => "/run/current-system/kernel-modules/lib/modules"
MOZ_PLUGIN_PATH => "/home/m/.nix-profile/lib/mozilla/plugins:/nix/var/nix/profiles/default/lib/mozilla/plugins:/run/current-system/sw/lib/mozilla/plugins"
NIXPKGS_CONFIG => "/etc/nix/nixpkgs-config.nix"
NIX_BUILD_CORES => "1"
NIX_BUILD_TOP => "/run/user/1000"
NIX_CC => "/nix/store/748qwsznn15h4jppkwji5mn9c34caiik-gcc-wrapper-4.9.3"
NIX_CFLAGS_COMPILE => " -isystem /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/include -isystem /nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/include -isystem /nix/store/alsvwzkiw4b7ip38l4nlfjijdvg3fvzn-zlib-1.2.8/include"
NIX_CONF_DIR => "/etc/nix"
NIX_LDFLAGS => "-rpath /nix/store/vwyvk6959cnfh7pcv34751ydc9crbcr0-wiki.template/lib64 -rpath /nix/store/vwyvk6959cnfh7pcv34751ydc9crbcr0-wiki.template/lib  -L/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib -L/nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib -L/nix/store/kaffxkkwq1mn2snxw9m80l90xmrwl9xf-python3.4-Pygments-2.0.2/lib -L/nix/store/15wxmny5ycpyw1dfdiq7b2145d3c1pny-python-recursive-pth-loader-1.0/lib -L/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib -L/nix/store/s1cw528a2zgbiwnvimmxwvprqybig5h1-python3.4m-setuptools-18.2/lib -L/nix/store/alsvwzkiw4b7ip38l4nlfjijdvg3fvzn-zlib-1.2.8/lib"
NIX_OTHER_STORES => "/run/nix/remote-stores/*/nix"
NIX_PATH => "/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels"
NIX_PROFILES => "/run/current-system/sw /nix/var/nix/profiles/default /home/m/.nix-profile"
NIX_REMOTE => "daemon"
NIX_STORE => "/nix/store"
NIX_USER_PROFILE_DIR => "/nix/var/nix/profiles/per-user/m"
PAGER => "less -R"
PATH => "/home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/bin:/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/bin:/nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/bin:/nix/store/kaffxkkwq1mn2snxw9m80l90xmrwl9xf-python3.4-Pygments-2.0.2/bin:/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/bin:/nix/store/s1cw528a2zgbiwnvimmxwvprqybig5h1-python3.4m-setuptools-18.2/bin:/nix/store/si6b773ffxy1rz7sg3d2x6i8ff84xqr3-patchelf-0.8/bin:/nix/store/vy22g81wg3m1dpv23mhlirc4jsa71c2k-paxctl-0.9/bin:/nix/store/748qwsznn15h4jppkwji5mn9c34caiik-gcc-wrapper-4.9.3/bin:/nix/store/p48nbf29nkv54vbvwqfqccwym58zf6bb-coreutils-8.24/bin:/nix/store/vmfzhzfh5w3hzxh7y0i4pf28h6jbqi62-findutils-4.4.2/bin:/nix/store/nfg10ny592lwllhmwibhapiviqaa20mw-diffutils-3.3/bin:/nix/store/5i5salk61869jjac0mgvj4n4agg2k2q0-gnused-4.2.2/bin:/nix/store/qrk6cndaf867z1blcfa9hpxrlar265j7-gnugrep-2.21/bin:/nix/store/rqvf08bq1jwzwnlvbazgcn0j3qx2bh4v-gawk-4.1.3/bin:/nix/store/53nxiy192q80dsdrbd5qn7vng3nvd1gm-gnutar-1.28/bin:/nix/store/vhfz8q5ijb3q35mmk0hrl9347l5gbrjk-gzip-1.6/bin:/nix/store/z8dixswg550xy81hryyky1rif3nkd6mm-bzip2-1.0.6/bin:/nix/store/9l702sp86v7cdqrrrn6a9rdgivmwdkm6-gnumake-4.1/bin:/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin:/nix/store/rwz61w52z1dz5kwpdn19ngwzfw5823ca-patch-2.7.5/bin:/nix/store/ivp3pna40wrq4i2whp4ijksfi4b8z58k-xz-5.2.1/bin:/nix/store/kpzihgr24vi2rrxcdfv3grnfcaw7jvf4-gcc-4.9.3/bin:/nix/store/qzjpd4npp8fdx8swy9nv52n71c2wi7cz-binutils-2.23.1/bin:/nix/store/qlxp7vb63fp8kx5vk9a0y3rj8svbvl27-glibc-2.21/bin:/home/m/bin:/var/setuid-wrappers:/home/m/.nix-profile/bin:/home/m/.nix-profile/sbin:/home/m/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec:/home/m/archive/bin"
PERL5LIB => "/home/m/.nix-profile/lib/perl5/site_perl:/nix/var/nix/profiles/default/lib/perl5/site_perl:/run/current-system/sw/lib/perl5/site_perl"
PKG_CONFIG_PATH => "/home/m/.nix-profile/lib/pkgconfig:/nix/var/nix/profiles/default/lib/pkgconfig:/run/current-system/sw/lib/pkgconfig"
PWD => "/home/m/dev/ruby/wiki.template"
PYTHONPATH => "/nix/store/kaffxkkwq1mn2snxw9m80l90xmrwl9xf-python3.4-Pygments-2.0.2/lib/python3.4/site-packages:/nix/store/15wxmny5ycpyw1dfdiq7b2145d3c1pny-python-recursive-pth-loader-1.0/lib/python3.4/site-packages:/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/site-packages:/nix/store/s1cw528a2zgbiwnvimmxwvprqybig5h1-python3.4m-setuptools-18.2/lib/python3.4/site-packages"
QML2_IMPORT_PATH => "/home/m/.nix-profile/lib/qt5/qml:/nix/var/nix/profiles/default/lib/qt5/qml:/run/current-system/sw/lib/qt5/qml"
QML_IMPORT_PATH => "/home/m/.nix-profile/lib/qt5/imports:/nix/var/nix/profiles/default/lib/qt5/imports:/run/current-system/sw/lib/qt5/imports"
QTWEBKIT_PLUGIN_PATH => "/home/m/.nix-profile/lib/mozilla/plugins/:/nix/var/nix/profiles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/mozilla/plugins/"
QT_PLUGIN_PATH => "/home/m/.nix-profile/lib/qt4/plugins:/home/m/.nix-profile/lib/kde4/plugins:/home/m/.nix-profile/lib/qt5/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt5/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins:/run/current-system/sw/lib/qt5/plugins"
RUBYLIB => "/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib:/nix/store/gf6pxv031pnpl4hhln4fmxxhq7alswg3-rubygems-2.4.1/lib"
RUBYOPT => "-rbundler/setup"
SHELL => "/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash"
SHLVL => "4"
SLIM_THEMESDIR => "/nix/store/3ddpc1qa9rm2r3n6x4np00p3jl2pb7lb-slim-theme"
SSH_ASKPASS => "/nix/store/1w7lal681n0zdf0s1k11yp4a9x45cwzg-x11-ssh-askpass-1.2.4.1/libexec/x11-ssh-askpass"
SSH_AUTH_SOCK => "/run/user/1000/ssh-agent"
SSL_CERT_FILE => "/etc/ssl/certs/ca-certificates.crt"
STRIGI_PLUGIN_PATH => "/home/m/.nix-profile/lib/strigi/:/nix/var/nix/profiles/default/lib/strigi/:/run/current-system/sw/lib/strigi/"
TEMP => "/run/user/1000"
TEMPDIR => "/run/user/1000"
TERM => "xterm"
TERMINFO_DIRS => "/home/m/.nix-profile/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo"
TMP => "/run/user/1000"
TMPDIR => "/run/user/1000"
TZDIR => "/etc/zoneinfo"
USER => "m"
WINDOWID => "16777229"
XAUTHORITY => "/home/m/.Xauthority"
XDG_CONFIG_DIRS => "/home/m/.nix-profile/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg"
XDG_DATA_DIRS => "/home/m/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share"
XDG_RUNTIME_DIR => "/run/user/1000"
XDG_SEAT => "seat0"
XDG_SESSION_ID => "1"
XDG_VTNR => "7"
XTERM_LOCALE => "de_DE.UTF-8"
XTERM_SHELL => "/var/run/current-system/sw/bin/bash"
XTERM_VERSION => "XTerm(317)"
_INHIBITION_LOCK_TAKEN => "1"
_ORIGINAL_GEM_PATH => "/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2:/nix/store/7z7p22ixw2nqw800r4mmvrih4iakwifp-ruby-2.2.2-p0/lib/ruby/gems/2.2.2:/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2:/nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/gems/2.2.0"
_PATH => "/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/bin:/nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/bin:/nix/store/kaffxkkwq1mn2snxw9m80l90xmrwl9xf-python3.4-Pygments-2.0.2/bin:/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/bin:/nix/store/s1cw528a2zgbiwnvimmxwvprqybig5h1-python3.4m-setuptools-18.2/bin:/nix/store/si6b773ffxy1rz7sg3d2x6i8ff84xqr3-patchelf-0.8/bin:/nix/store/vy22g81wg3m1dpv23mhlirc4jsa71c2k-paxctl-0.9/bin:/nix/store/748qwsznn15h4jppkwji5mn9c34caiik-gcc-wrapper-4.9.3/bin"
__ETC_PROFILE_DONE => "1"
buildInputs => ""
builder => "/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash"
name => "wiki.template"
nativeBuildInputs => "/nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5 /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0 /nix/store/kaffxkkwq1mn2snxw9m80l90xmrwl9xf-python3.4-Pygments-2.0.2 /nix/store/alsvwzkiw4b7ip38l4nlfjijdvg3fvzn-zlib-1.2.8"
out => "/nix/store/vwyvk6959cnfh7pcv34751ydc9crbcr0-wiki.template"
propagatedBuildInputs => ""
propagatedNativeBuildInputs => ""
shell => "/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash"
src => "/nix/store/9a5a0jzvgidriy9b102n0pb8s6kqrl8a-wiki.template"
stdenv => "/nix/store/hfi5bzjbci1x8fk9m7gxxjw29wnyma1g-stdenv"
system => "x86_64-linux"
version => "0.0.0"

===== GEMFILE.LOCK:

GEM
  remote: http://rubygems.org/
  specs:
    adsf (1.2.0)
      rack (>= 1.0.0)
    chunky_png (1.3.4)
    coderay (1.1.0)
    colored (1.2)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    cri (2.7.0)
      colored (~> 1.2)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    kramdown (1.8.0)
    method_source (0.8.2)
    mini_portile (0.6.2)
    multi_json (1.11.2)
    nanoc (4.0.0rc2)
      cri (~> 2.3)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    posix-spawn (0.3.11)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rack (1.6.4)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    sass (3.4.18)
    slop (3.6.0)
    tilt (2.0.1)
    yajl-ruby (1.2.1)
    zurb-foundation (4.3.2)
      sass (>= 3.2.0)

PLATFORMS
  ruby

DEPENDENCIES
  adsf
  compass
  haml
  kramdown
  nanoc (~> 4.0.0rc2)
  nokogiri
  pry
  pygments.rb
  zurb-foundation

BUNDLED WITH
   1.10.5

===== LOAD PATHS:

  0. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/zurb-foundation-4.3.2/lib
  1. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/pygments.rb-0.6.3/lib
  2. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/yajl-ruby-1.2.1
  3. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/yajl-ruby-1.2.1/lib
  4. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/pry-0.10.1/lib
  5. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/slop-3.6.0/lib
  6. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/posix-spawn-0.3.11
  7. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/posix-spawn-0.3.11/lib
  8. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/nokogiri-1.6.6.2
  9. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.6.2/lib
  10. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib
  11. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mini_portile-0.6.2/lib
  12. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/method_source-0.8.2/lib
  13. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/kramdown-1.8.0/lib
  14. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib
  15. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/tilt-2.0.1/lib
  16. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/cri-2.7.0/lib
  17. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/compass-1.0.3/lib
  18. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/rb-inotify-0.9.5/lib
  19. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/ffi-1.9.10
  20. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/ffi-1.9.10/lib
  21. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/rb-fsevent-0.9.6/lib
  22. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/compass-import-once-1.0.5/lib
  23. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/compass-core-1.0.3/lib
  24. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/sass-3.4.18/lib
  25. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/multi_json-1.11.2/lib
  26. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/colored-1.2/lib
  27. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/coderay-1.1.0/lib
  28. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/chunky_png-1.3.4/lib
  29. /nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/gems/bundler-1.10.5/lib
  30. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/adsf-1.2.0/lib
  31. /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib
  32. /nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib
  33. /nix/store/gf6pxv031pnpl4hhln4fmxxhq7alswg3-rubygems-2.4.1/lib
  34. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/site_ruby/2.2.0
  35. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/site_ruby/2.2.0/x86_64-linux
  36. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/site_ruby
  37. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/vendor_ruby/2.2.0
  38. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
  39. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/vendor_ruby
  40. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/2.2.0
  41. /nix/store/f1apc0zzila8ramghp8dlrqb8nz9sb1y-ruby-2.2.0-p0/lib/ruby/2.2.0/x86_64-linux
```

The input for nanoc is here:

https://github.com/matthiasbeyer/wiki.template/commit/3f1d51762ec168acf06d689f7ff171e384c70d5f

Steps to reproduce:

```
bundle install --path vendor/bundle
bundle exec nanoc
```

The repo should contain everything you need to reproduce this error.

**Comment by k0kubun** [comment]
Umm? This is syntax error in `/articles/the_wiki.haml` on line 34 as described in the backtrace.

Because I couldn't find the_wiki.haml from https://github.com/matthiasbeyer/wiki.template/commit/3f1d51762ec168acf06d689f7ff171e384c70d5f, closing for now.

**Comment by matthiasbeyer** [comment]
After 2 years finally some love here... I don't care anymore, though.
