### ISSUE TITLE
Haml::InvalidAttributeNameError with dynamic arguments

### ISSUE THREAD

**Issue by cdrapier** [haml/haml#917]
When running something like this:

```
- base_url = "http://www.google.com"
%iframe#test{src: "#{File.join base_url, '/abc/'}"}
```

I get the following error :

```
 Haml::InvalidAttributeNameError:
            Invalid attribute name '/abc/' was rendered
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/attribute_builder.rb:100:in `block in verify_attribute_names!'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/attribute_builder.rb:98:in `each'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/attribute_builder.rb:98:in `verify_attribute_names!'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/attribute_compiler.rb:63:in `compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:111:in `compile_tag'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:28:in `compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:30:in `block (2 levels) in compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:30:in `each'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:30:in `block in compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:40:in `compile_root'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:30:in `compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/compiler.rb:21:in `call'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/temple-0.8.0/lib/temple/engine.rb:50:in `block in call'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/temple-0.8.0/lib/temple/engine.rb:50:in `each'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/temple-0.8.0/lib/temple/engine.rb:50:in `inject'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/temple-0.8.0/lib/temple/engine.rb:50:in `call'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/temple_engine.rb:40:in `compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/engine.rb:61:in `initialize'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/plugin.rb:16:in `new'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/plugin.rb:16:in `compile'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/haml-5.0.0/lib/haml/plugin.rb:23:in `call'
          # /Users/cdrapier/.gem/ruby/2.3.1/gems/actionview-4.2.5.1/lib/action_view/template.rb:270:in `compile'
```

For the little I have looked inside the gem, it seems something strange is going on in attribute_parser.rb, and for some reason a bit unclear to me, the '/abc/' is treated as a key/name of an attribute. But It was a bit difficult to get deeper inside what is happening.

One easy fix on my code part would be to use a variable to contain the result of "#{File.join base_url, '/abc/'}", but I thought this might be a bug that would need to be fix.

**Comment by k0kubun** [comment]
Oh, sorry... that's definitely a bug. Fixed in https://github.com/haml/haml/commit/c67e67274353526d5a5da2a8d36cabcc313ed7ab. Thank you for reporting.
