### ISSUE TITLE
undefined method `children' for false:HamlLint::ParsedRuby

### ISSUE THREAD

**Issue by mensfeld** [haml/haml#926]
Hey guys - with new haml-lint version I get following error when I use ```--reporter checkstyle``` option:

```
undefined method `children' for false:HamlLint::ParsedRuby
/home/mencio/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/delegate.rb:87:in `method_missing'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/tree/tag_node.rb:237:in `existing_attributes'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/tree/tag_node.rb:38:in `has_hash_attribute?'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/linter/inline_styles.rb:9:in `visit_tag'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:19:in `visit'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/linter.rb:28:in `run'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:84:in `block in collect_lints'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:83:in `map'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:83:in `collect_lints'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:119:in `process_file'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:108:in `block in process_files'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:107:in `each'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:107:in `process_files'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:132:in `report'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/runner.rb:23:in `run'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/cli.rb:106:in `scan_for_lints'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/lib/haml_lint/cli.rb:23:in `run'
/home/mencio/.rvm/gems/ruby-2.4.0/gems/haml_lint-0.25.0/bin/haml-lint:7:in `<top (required)>'
/home/mencio/.rvm/gems/ruby-2.4.0/bin/haml-lint:22:in `load'
/home/mencio/.rvm/gems/ruby-2.4.0/bin/haml-lint:22:in `<main>'
/home/mencio/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/mencio/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.25.0
- Haml version: 5.0.1
- RuboCop version: 0.48.1
- Ruby version: 2.4.0
```

Everything works well when I don't use the checkstyle reporter.

The way I run it:

```
haml-lint ./ProjectWithProblems --reporter checkstyle
```

**Comment by mensfeld** [comment]
Not here - haml-lint problem. Sorry :(
