### ISSUE TITLE
:ruby filter with no content causes TypeError

### ISSUE THREAD

**Issue by aselder** [haml/haml#942]
We had a haml file that started:

```
:ruby

%section.completed-test
  .completed-test__header
```

When haml tries to render this file, we get the following:
```
     TypeError:
       no implicit conversion of nil into String
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/filters.rb:285:in `+'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/filters.rb:285:in `block in compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/filters.rb:284:in `instance_eval'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/filters.rb:284:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/filters.rb:142:in `internal_compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:180:in `compile_filter'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:29:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:31:in `block (2 levels) in compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:31:in `each'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:31:in `block in compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:41:in `compile_root'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:31:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/compiler.rb:22:in `call'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/temple-0.8.0/lib/temple/engine.rb:50:in `block in call'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/temple-0.8.0/lib/temple/engine.rb:50:in `each'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/temple-0.8.0/lib/temple/engine.rb:50:in `inject'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/temple-0.8.0/lib/temple/engine.rb:50:in `call'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/temple_engine.rb:41:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/engine.rb:61:in `initialize'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/plugin.rb:16:in `new'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/plugin.rb:16:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/haml-5.0.1/lib/haml/plugin.rb:23:in `call'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:270:in `compile'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:245:in `block (2 levels) in compile!'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:333:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:244:in `block in compile!'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:232:in `synchronize'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:232:in `compile!'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:144:in `block in render'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:333:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/template.rb:143:in `render'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/aselder/.rvm/gems/ruby-2.3.4@usertesting-orders/gems/actionview-4.2.9/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
```

**Comment by k0kubun** [comment]
Fixed. Thank you for reporting.
