### ISSUE TITLE
`undefined method `rstrip' for nil:NilClass (NoMethodError)` on empty :javascript filter block

### ISSUE THREAD

**Issue by wjordan** [haml/haml#985]
Expected (empty `:javascript` filter block renders empty `<script>` tag block, works in Haml 4):
```
$ echo ':javascript' | haml _4.0.7_ -s
<script>
  
</script>
$ ruby -e "gem 'haml', '~> 4'; require 'haml'; puts Haml::Engine.new(':javascript').render"
<script>
  
</script>
```
Error (Haml 5):
```
$ echo ':javascript' | haml _5.0.4_ -s
Exception on line 216: undefined method `rstrip' for nil:NilClass
  Use --trace for backtrace.
$ ruby -e "gem 'haml', '~> 5'; require 'haml'; puts Haml::Engine.new(':javascript').render"
Traceback (most recent call last):
	20: from -e:1:in `<main>'
	19: from -e:1:in `new'
	18: from [RUBY]/gems/haml-5.0.4/lib/haml/engine.rb:61:in `initialize'
	17: from [RUBY]/gems/haml-5.0.4/lib/haml/temple_engine.rb:41:in `compile'
	16: from [RUBY]/gems/temple-0.8.0/lib/temple/engine.rb:50:in `call'
	15: from [RUBY]/gems/temple-0.8.0/lib/temple/engine.rb:50:in `inject'
	14: from [RUBY]/gems/temple-0.8.0/lib/temple/engine.rb:50:in `each'
	13: from [RUBY]/gems/temple-0.8.0/lib/temple/engine.rb:50:in `block in call'
	12: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:22:in `call'
	11: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:31:in `compile'
	10: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:41:in `compile_root'
	 9: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:31:in `block in compile'
	 8: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:31:in `each'
	 7: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:31:in `block (2 levels) in compile'
	 6: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:29:in `compile'
	 5: from [RUBY]/gems/haml-5.0.4/lib/haml/compiler.rb:178:in `compile_filter'
	 4: from [RUBY]/gems/haml-5.0.4/lib/haml/filters.rb:142:in `internal_compile'
	 3: from [RUBY]/gems/haml-5.0.4/lib/haml/filters.rb:163:in `compile'
	 2: from [RUBY]/gems/haml-5.0.4/lib/haml/filters.rb:163:in `instance_eval'
	 1: from [RUBY]/gems/haml-5.0.4/lib/haml/filters.rb:185:in `block in compile'
[RUBY]/gems/haml-5.0.4/lib/haml/filters.rb:216:in `render_with_options': undefined method `rstrip' for nil:NilClass (NoMethodError)
```

**Comment by wjordan** [comment]
`:css` filter also has this same issue:
```
$ echo ':css' | haml _4.0.7_ -s
<style>
  
</style>
$ echo ':css' | haml _5.0.4_ -s
Exception on line 237: undefined method `rstrip' for nil:NilClass
  Use --trace for backtrace.
```

**Comment by k0kubun** [comment]
It's already fixed on master. Ping @amatsuda to cut a new release.
